name: Super-Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  statuses: write

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: github/super-linter/slim@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          VALIDATE_ALL_CODEBASE: true       # lint everything for now; flip to false later
          IGNORE_GITIGNORED_FILES: true
          FILTER_REGEX_EXCLUDE: "^(venv/|.venv/|__pycache__/|dist/|build/)"

          # enable Python linters wanted
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: true
          # VALIDATE_PYTHON_PYLINT: false
